/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.Admin;

import Controlador.Admin_O;
import Controlador.Admin_PI;
import Controlador.Ctrl_AdminTours;

/**
 *
 * @author LENOVO
 */
public class IAdm_Comite extends javax.swing.JFrame {

    /**
     * Creates new form I_AdmSys
     */
    public IAdm_Comite() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jPanel1 = new javax.swing.JPanel();
                jPanel2 = new javax.swing.JPanel();
                jLabel1 = new javax.swing.JLabel();
                jButtonObras = new javax.swing.JButton();
                jButtonPI = new javax.swing.JButton();
                jButtonTours = new javax.swing.JButton();
                jButtonVolver = new javax.swing.JButton();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                setTitle("COPRED - Administración Comité");
                setMaximumSize(new java.awt.Dimension(650, 160));
                setPreferredSize(new java.awt.Dimension(650, 160));
                setResizable(false);

                jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                jLabel1.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
                jLabel1.setText("Seleccione una opción:");
                jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

                jButtonObras.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
                jButtonObras.setText("Administrar Obras");
                jButtonObras.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButtonObrasActionPerformed(evt);
                        }
                });
                jPanel2.add(jButtonObras, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 160, -1));

                jButtonPI.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
                jButtonPI.setText("Administrar Puntos de Interés");
                jButtonPI.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButtonPIActionPerformed(evt);
                        }
                });
                jPanel2.add(jButtonPI, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, -1, -1));

                jButtonTours.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
                jButtonTours.setText("Administrar Tours");
                jButtonTours.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButtonToursActionPerformed(evt);
                        }
                });
                jPanel2.add(jButtonTours, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 50, 170, -1));

                jButtonVolver.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
                jButtonVolver.setText("Salir");
                jButtonVolver.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButtonVolverActionPerformed(evt);
                        }
                });
                jPanel2.add(jButtonVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 90, 70, -1));

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                );
                jPanel1Layout.setVerticalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                );

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                );

                getAccessibleContext().setAccessibleName("Administrar Sistema");

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void jButtonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverActionPerformed
                IAcceso iAcceso = new IAcceso();

                iAcceso.setVisible(true);
                iAcceso.setLocationRelativeTo(null);
                this.dispose();
        }//GEN-LAST:event_jButtonVolverActionPerformed

        private void jButtonToursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonToursActionPerformed
                Ctrl_AdminTours ctrlAdminTours = Ctrl_AdminTours.getInstance();

                ctrlAdminTours.adminTour();
                this.dispose();
        }//GEN-LAST:event_jButtonToursActionPerformed

        private void jButtonPIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPIActionPerformed
                Admin_PI ctrlPI = Admin_PI.getInstance();

                ctrlPI.instanceAdmPI();
                this.dispose();
        }//GEN-LAST:event_jButtonPIActionPerformed

        private void jButtonObrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonObrasActionPerformed
                Admin_O ctrlObras = Admin_O.getInstance();

                ctrlObras.instanceAdmObras();
                this.dispose();
        }//GEN-LAST:event_jButtonObrasActionPerformed
    
        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton jButtonObras;
        private javax.swing.JButton jButtonPI;
        private javax.swing.JButton jButtonTours;
        private javax.swing.JButton jButtonVolver;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JPanel jPanel2;
        // End of variables declaration//GEN-END:variables
}
